spring.application.name=salud
spring.data.mongodb.uri=mongodb+srv://admin:<db_password>@parcialfinal.hrusfox.mongodb.net/?retryWrites=true&w=majority&appName=ParcialFinal
spring.data.mongodb.database=ParcialFinal