spring.application.name=ecicredit

spring.data.mongodb.uri=mongodb+srv://admin:parcial2@parcial2.wormklx.mongodb.net/?retryWrites=true&w=majority&appName=Parcial2
spring.data.mongodb.database=Parcial2